- hosts: minecraft
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Java
      apt:
        name: openjdk-11-jre-headless
        state: present

    - name: Create minecraft user
      user:
        name: minecraft
        home: /home/minecraft
        createhome: yes

    - name: Download Minecraft server
      get_url:
        url: https://launcher.mojang.com/v1/objects/e3a2fbdc18c27b14b8b4b55b1e2b8d1bdcd85c87/server.jar
        dest: /home/minecraft/server.jar
        mode: '0755'

    - name: Create a systemd service file for Minecraft
      copy:
        dest: /etc/systemd/system/minecraft.service
        content: |
          [Unit]
          Description=Minecraft Server
          After=network.target

          [Service]
          User=minecraft
          WorkingDirectory=/home/minecraft
          ExecStart=/usr/bin/java -Xmx1024M -Xms1024M -jar server.jar nogui
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
      notify:
        - Start Minecraft server

  handlers:
    - name: Start Minecraft server
      systemd:
        name: minecraft
        state: started
        enabled: yes
